### ISSUE TITLE
前端支持事件中心、操作记录查询

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris-console#151]
polaris-console 需要支持直接对接腾讯云CLS以及开源的Loki插件

## 数据来源插件配置

对接腾讯云CLS配置

```yaml
eventHub:
  type: cls
  options:
    topic:
    accessInfo:
      local:
        secretId:
        secretKey:
      remoteHttp:
        url:
history:
  type: cls
  options:
    topic:
    accessInfo:
      local:
        secretId:
        secretKey:
      remoteHttp:
        url:
```

对接Loki配置

```yaml
eventHub:
  type: loki
  options:
    topic:
    tenantID:
    labels:
      key: value
history:
  type: loki
  options:
    topic:
    tenantID:
    labels:
      key: value
```
